package parser

import (
	"fmt"

	"github.com/njreid/gokdl2/document"
	"github.com/njreid/gokdl2/internal/tokenizer"
)

func tokensAdjacent(prev, curr tokenizer.Token) bool {
	if prev.Line != curr.Line {
		return false
	}
	return curr.Column == prev.Column+len(prev.Data)
}

func isValueLikeToken(id tokenizer.TokenID) bool {
	switch id {
	case tokenizer.BareIdentifier, tokenizer.RawString, tokenizer.QuotedString,
		tokenizer.Decimal, tokenizer.Hexadecimal, tokenizer.Octal, tokenizer.Binary,
		tokenizer.SuffixedDecimal, tokenizer.Boolean, tokenizer.Null, tokenizer.Keyword,
		tokenizer.BraceClose:
		return true
	default:
		return false
	}
}

func requiresV2Separation(prev, curr tokenizer.Token) bool {
	if !tokensAdjacent(prev, curr) {
		return false
	}

	if isValueLikeToken(prev.ID) {
		switch curr.ID {
		case tokenizer.BareIdentifier, tokenizer.RawString, tokenizer.QuotedString,
			tokenizer.Decimal, tokenizer.Hexadecimal, tokenizer.Octal, tokenizer.Binary,
			tokenizer.SuffixedDecimal, tokenizer.Boolean, tokenizer.Null, tokenizer.Keyword:
			return true
		}
	}

	if prev.ID == tokenizer.ParensClose && curr.ID == tokenizer.TokenComment {
		return true
	}

	return false
}

func isTriviaToken(id tokenizer.TokenID) bool {
	switch id {
	case tokenizer.Whitespace, tokenizer.Newline, tokenizer.SingleLineComment, tokenizer.MultiLineComment:
		return true
	default:
		return false
	}
}

type Parser struct {
}

// New creates a new Parser
func New() *Parser {
	return &Parser{}
}

// NewContext creates a new ParseContext
func (p *Parser) NewContext() *ParseContext {
	return p.NewContextOptions(defaultParseContextOptions)
}

func (p *Parser) NewContextOptions(opts ParseContextOptions) *ParseContext {
	return &ParseContext{
		doc:  document.New(),
		opts: opts,
	}
}

var eofToken = tokenizer.Token{
	ID:   tokenizer.EOF,
	Data: []byte{},
}

func (p *Parser) tokenContext(context []tokenizer.Token, idx int) string {
	if len(context) == 0 {
		return ""
	}
	start := idx - 5
	if start < 0 {
		start = 0
	}
	end := start + 10
	if end > len(context) {
		end = len(context)
	}
	b := make([]byte, 0, 128)
	b = append(b, "..."...)
	caretOffset := 3
	for i := start; i < end; i++ {
		for _, c := range context[i].Data {
			if c == '\t' || c == '\r' || c == '\n' {
				c = ' '
			}
			b = append(b, c)
		}
		if i < idx {
			caretOffset += len(context[i].Data)
		}
	}
	b = append(b, "..."...)
	b = append(b, '\n')
	for i := 0; i < caretOffset; i++ {
		b = append(b, ' ')
	}
	b = append(b, '^')
	return string(b)
}

func (p *Parser) annotatedError(err error, t tokenizer.Token, context []tokenizer.Token, contextIndex int) error {
	return fmt.Errorf("parse failed: %w at line %d, column %d:\n%s", err, t.Line, t.Column, p.tokenContext(context, contextIndex))
}

// Parse parses a single token (usually generated by tokenizer.Scanner) into the given context, and returns a non-nil
// error on failure
func (p *Parser) parse(c *ParseContext, token tokenizer.Token) error {
	if c.opts.Version == tokenizer.VersionV2 {
		recent := c.recent.Get()
		if len(recent) >= 2 {
			prev := recent[len(recent)-2]
			if requiresV2Separation(prev, token) {
				return fmt.Errorf("missing required separator before %s", token.ID)
			}
		}
	}
	if c.afterIgnoredChildBlock {
		switch token.ID {
		case tokenizer.Whitespace, tokenizer.SingleLineComment, tokenizer.MultiLineComment:
		case tokenizer.Newline, tokenizer.EOF, tokenizer.Continuation:
			if token.ID == tokenizer.Newline || token.ID == tokenizer.EOF || token.ID == tokenizer.Continuation {
				c.afterIgnoredChildBlock = false
			}
		default:
			return fmt.Errorf("unexpected %s after ignored child block", token.ID)
		}
	}

	if c.continuation {
		switch token.ID {
		case tokenizer.Newline:
			if c.continuationNewlineSeen {
				c.stopContinuation()
			} else {
				c.continuationNewlineSeen = true
			}
		case tokenizer.Whitespace, tokenizer.SingleLineComment, tokenizer.MultiLineComment:
			// continue waiting for the first token of the next (continued) line
		default:
			// this is the first token of the next (continued) line
			c.stopContinuation()
			c.justContinuedLine = true
		}
	} else if !isTriviaToken(token.ID) {
		c.justContinuedLine = false
	}

	validTransitions := stateTransitions[c.state]

	handler, ok := validTransitions[token.ID]
	if !ok {
		// if there's no handler for this token's specific ID, check for a handler for the class of token instead
		tokenClasses := token.ID.Classes()
		for _, tokenClass := range tokenClasses {
			if handler, ok = validTransitions[tokenClass]; ok {
				break
			}
		}
	}

	var err error
	if handler == nil {
		err = fmt.Errorf("unexpected %s in state %s", token.ID, c.state)
	} else {
		err = handler(c, token)
	}

	return err
}

func (p *Parser) Parse(c *ParseContext, token tokenizer.Token) error {
	c.recent.Add(token)
	if err := p.parse(c, token); err != nil {
		if err == ErrReenterState {
			return err
		}
		tokens := c.recent.Get()
		return p.annotatedError(err, token, tokens, len(tokens)-1)
	}

	return nil
}

// ParseAll parses a slice of tokens and returns the resulting Document, or a non-nil error on failure
func (p *Parser) ParseAll(tokens []tokenizer.Token) (*document.Document, error) {
	c := p.NewContext()
	return p.ParseAllContext(c, tokens)
}

var ErrReenterState = fmt.Errorf("reenter state")

// ParseAllContext parses a slice of tokens using the given context and returns the resulting Document, or a non-nil
// error on failure
func (p *Parser) ParseAllContext(c *ParseContext, tokens []tokenizer.Token) (*document.Document, error) {
	for i := 0; i < len(tokens); i++ {
		t := tokens[i]
		if err := p.Parse(c, t); err != nil {
			if err == ErrReenterState {
				i--
				continue
			}
			return nil, p.annotatedError(err, t, tokens, i)
		}
	}

	eof := eofToken

	if len(tokens) > 0 {
		lastToken := tokens[len(tokens)-1]
		eof.Line = lastToken.Line
		eof.Column = lastToken.Column + len(lastToken.Data)
	}

	if err := p.Parse(c, eof); err != nil {
		return nil, p.annotatedError(err, eof, tokens, len(tokens)-1)
	}

	c.doc.Version = int(c.opts.Version)
	return c.doc, nil
}
